import Link from "next/link";
import { ArrowRight, MessageCircle } from "lucide-react";
import { categories, events, members, projects, stats } from "@/lib/data";
import { SectionHeading } from "@/components/app-shell";
import { EventCard, MemberCard, ProjectCard } from "@/components/cards";

export default function Home() {
  return <>
    <section className="hero"><div><div className="eyebrow">A home for the relentlessly curious <span style={{ color: "var(--lime)" }}>●</span></div><h1>Make your next<br /><em>move together.</em></h1><p className="hero-copy">The DropOut College is a private network for people who learn fast, build boldly, and want to find their people before they find the spotlight.</p><div className="hero-actions"><Link href="/explore" className="button button-primary">Explore the network <ArrowRight size={15} /></Link><Link href="https://discord.gg/3xfu5TMgF" target="_blank" rel="noreferrer" className="button button-ghost"><MessageCircle size={15} />Join Discord</Link></div></div><div className="hero-art" aria-label="Abstract network visualization"><span className="hero-orbit" /><div style={{ position: "absolute", left: 20, top: 18, color: "var(--muted)", font: "10px DM Mono" }}>LIVE / 04.8K</div><div style={{ position: "absolute", right: 20, top: 18, color: "var(--muted)", font: "10px DM Mono" }}>NODE 001</div></div></section>
    <section className="stats-grid">{stats.map(([value, label]) => <div className="stat" key={label}><strong>{value}</strong><span>{label}</span></div>)}</section>
    <section className="section"><SectionHeading eyebrow="Find your frequency" title="Communities with range." action={<Link href="/explore" className="section-link">View all <ArrowRight size={13} /></Link>} /><div className="category-grid">{categories.map((category) => <Link href="/explore" className="category-card" key={category.name}><span className="category-icon">{category.icon}</span><h3>{category.name}</h3><p>{category.description}</p><div className="category-meta"><span>{category.members} members</span><span>Explore ↗</span></div></Link>)}</div></section>
    <section className="section"><SectionHeading eyebrow="People worth knowing" title="The room is full." action={<Link href="/explore" className="section-link">Meet members <ArrowRight size={13} /></Link>} /><div className="member-grid">{members.map(member => <MemberCard key={member.handle} member={member} />)}</div></section>
    <section className="section"><SectionHeading eyebrow="Built in the network" title="Ideas with a pulse." action={<Link href="/projects" className="section-link">All projects <ArrowRight size={13} /></Link>} /><div className="project-grid">{projects.map(project => <ProjectCard key={project.name} project={project} />)}</div></section>
    <section className="section"><SectionHeading eyebrow="Put something on the calendar" title="Always something happening." action={<Link href="/events" className="section-link">See all events <ArrowRight size={13} /></Link>} /><div className="event-grid">{events.map(event => <EventCard key={event.title} event={event} />)}</div></section>
    <section className="section discord-banner"><div><div className="eyebrow">The live layer</div><h2>Come for the signal.<br />Stay for the people.</h2><p>Our Discord is where projects find teammates, questions find answers, and the best conversations happen between the lines.</p></div><Link href="https://discord.gg/3xfu5TMgF" target="_blank" rel="noreferrer" className="button button-primary">Enter the Discord <ArrowRight size={15} /></Link></section>
  </>;
}
